services:
  zookeeper-demo:
    network_mode: host
    image: zookeeper
    ports:
      - 2181
  kafka-demo:
    network_mode: host
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper-demo
    ports:
      - 9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
