services:
  zookeeper-demo:
    image: zookeeper
    ports:
      - 2181
  kafka-broker-demo:
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper-demo
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-demo:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
